image: node:10.16.3

pages:
  stage: deploy
  script:
    - npm install
    - unset CI 
    - npm run build
    - rm -rf public
    - mv build public
  artifacts:
    paths:
      - public
  only:
    - master
